services:
  - type: web
    name: gradeX
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn gradeX.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: gradeX.settings
      - key: PYTHON_VERSION
        value: 3.11.9  


python manage.py collectstatic --noinput && python manage.py migrate
pip install whitenoise


static:
  - type: static_dir
    name: static
    path: /static/
    dir: staticfiles/
