services:
  - type: web
    name: gradeX
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn gradeX.wsgi
    envVars:
      - key: DEBUG
        value: False
