# Generated by Django 4.2.7 on 2025-07-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentrecord",
            old_name="register_number",
            new_name="reg_number",
        ),
        migrations.RemoveField(
            model_name="studentrecord",
            name="date_submitted",
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="branch",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="sgpa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
    ]
