# Generated by Django 4.2.7 on 2025-07-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("register_number", models.CharField(max_length=20)),
                ("branch", models.CharField(max_length=10)),
                ("sgpa", models.DecimalField(decimal_places=2, max_digits=4)),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
